# AI Hedge Fund stack (no local Ollama)

services:
  backend:
    container_name: ai-hedge-fund-backend
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: poetry run uvicorn app.backend.main:app --host 0.0.0.0 --port 8000
    environment:
      - FRONTEND_ORIGIN: ${PUBLIC_URL}
      - FINANCIAL_DATASETS_API_KEY: ${FINANCIAL_DATASETS_API_KEY}
      - OPENAI_API_KEY: ${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      - DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      - GROQ_API_KEY: ${GROQ_API_KEY}
      - XAI_API_KEY: ${XAI_API_KEY}
      - GIGACHAT_API_KEY: ${GIGACHAT_API_KEY}
      - OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      - AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_NAME: ${AZURE_OPENAI_DEPLOYMENT_NAME}
    working_dir: /app
    volumes:
      - ./:/app
    restart: unless-stopped

  frontend:
    container_name: ai-hedge-fund-frontend
    image: node:20-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://backend:8000}
    volumes:
      - ./app/frontend:/usr/src/app
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: ai-hedge-fund-network
