version: "3.8"

services:
  app:
    container_name: ai-hedge-fund
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Frontend/Backend URLs
      PUBLIC_URL: ${PUBLIC_URL}
      VITE_API_URL: ${VITE_API_URL}
      FRONTEND_ORIGIN: ${PUBLIC_URL}
      # App server bindings
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      FRONTEND_HOST: 0.0.0.0
      FRONTEND_PORT: ${FRONTEND_PORT:-5173}
      NODE_ENV: production
      # Provider keys
      FINANCIAL_DATASETS_API_KEY: ${FINANCIAL_DATASETS_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      XAI_API_KEY: ${XAI_API_KEY}
      GIGACHAT_API_KEY: ${GIGACHAT_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${AZURE_OPENAI_DEPLOYMENT_NAME}
      # Disable auto-opening the browser in containers
      DISABLE_BROWSER: "1"
    restart: unless-stopped

networks:
  default:
    name: ai-hedge-fund-network
